# Generated by Django 4.2.23 on 2025-07-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_image'),
        ('about', '0003_about_profile_image_alter_about_title'),
    ]

    operations = [
    ]
